/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

/**
 * @example
 *     {
 *         totalCalls: 3,
 *         completedCalls: 2,
 *         inProgressCalls: 1,
 *         queueStatuses: {
 *             complete: 2,
 *             queued: 1,
 *             callError: 0
 *         },
 *         callLengths: {
 *             average: 7,
 *             averageNonzero: 7,
 *             summary: {
 *                 05: 2,
 *                 510: 0,
 *                 1015: 1,
 *                 1520: 0,
 *                 2030: 0,
 *                 3045: 0,
 *                 4560: 0,
 *                 6090: 0,
 *                 90120: 0,
 *                 120: 0
 *             },
 *             all: [5, 5, 11]
 *         },
 *         callIds: ["73c809a9-db35-4edb-8fa6-95a6a942daf8", "73c809a9-db35-4edb-8fa6-95a6a942daf9", "73c809a9-db35-4edb-8fa6-95a6a942daf0"],
 *         errorMessages: ["Cannot transfer to +12223334444 - Call is no longer active."],
 *         endpoints: {
 *             "API": "3"
 *         }
 *     }
 */
export interface AnalysisObject {
    /** The total number of calls in the batch, including completed and in-progress calls. */
    totalCalls: number;
    /** The total number of completed calls in the batch. */
    completedCalls: number;
    /** The total number of in-progress calls in the batch. */
    inProgressCalls: number;
    /** An object containing the number of calls in each queue status. */
    queueStatuses: BlandAI.QueueStatus;
    /** Contains `average`, `average_nonzero`, `summary` and `all` fields. */
    callLengths: BlandAI.CallLength;
    /** Contains each `call_id` in the batch. */
    callIds: string[];
    /** Contains any error messages that calls in the batch may have. */
    errorMessages: string[];
    /** Contains the number of calls that have been sent to each endpoint. Applicable only to API integrations. */
    endpoints: Record<string, string>;
}
