/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         goal: "Renewal Confirmation",
 *         questions: [["Who answered the call?", "human or voicemail"], ["Positive feedback about the product: ", "string"], ["Negative feedback about the product: ", "string"], ["Customer confirmed they were satisfied", "boolean"]]
 *     }
 */
export interface AnalyzeBatchRequest {
    /** This is the overall purpose of the batch of calls. Provides context for the analysis to guide how the questions/transcripts are interpreted. */
    goal: string;
    /**
     * An array of questions to be analyzed for each call in the batch.
     *
     * Each question should be an array with two elements: the question text and the expected answer type (e.g., “string”, “boolean”).
     *
     * Fairly flexible in terms of the expected answer type, and unanswerable questions will default to `null`.
     */
    questions: string[][];
}
