/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface BatchObject {
    /** The unique identifier for the batch. */
    batchId: string;
    campaignId: string;
    /** The date and time the batch was created. */
    createdAt: Date;
    /** The label you assigned to the batch (if any). */
    label: string;
    /** The prompt or task used for all the phone calls in the batch. */
    basePrompt: string;
    /**
     * Enterprise customers with custom endpoints will see the endpoint code here (if specified).
     *
     * The default value is `API`.
     */
    endpointCode: string;
    /** The base call parameters used to create the batch. */
    callParams: BlandAI.CallParams;
}
