/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface BatchCallData {
    /** The phone number to call. */
    phoneNumber: BlandAI.PhoneNumber;
    /** The name of the business or person being called. */
    business?: string;
    /** The service or product being discussed. */
    service?: string;
    /** The date of the event or deadline being discussed. */
    date?: string;
}
