/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface BatchParams {
    /** The unique identifier of the batch - used as the `batch_id` parameter in other API calls. */
    id: string;
    campaignId?: string;
    /** The creation timestamp of the batch. */
    createdAt: Date;
    /** The label or description of the batch. */
    label: string;
    /** The base prompt used for calls in this batch. */
    basePrompt: string;
    /** The endpoint code used for API integration. */
    endpointCode: string;
    /** An object containing parameters for the calls in the batch. */
    callParams: BlandAI.CallParams;
}
