/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface BatchAnalysisObject {
    callId: string;
    batchId: string;
    goal: string;
    /** The results of the AI analysis. */
    answers: string[];
    /** The original questions asked by the AI. */
    questions: string[];
}
