/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface CallLength {
    /** The average call length in minutes. */
    average: number;
    /** The average call length in minutes, excluding calls with a length of less than one second. */
    averageNonzero: number;
    /** A summary of the call lengths, grouped into ranges. */
    summary: BlandAI.CallLengthSummary;
    /** Contains each call length, in case you want to use a different grouping than the default. */
    all: number[];
}
