/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface CallData {
    /** The timestamp when the individual call was created. */
    createdAt: Date;
    /** The phone number the call was made to. */
    to: string;
    /** The phone number the call was made from. */
    from: string;
    /** Indicates if the call was completed. */
    completed: boolean;
    /** The unique identifier for each individual call. */
    callId: string;
    /** The duration of the call in minutes. */
    callLength: number;
    /** Contains a string value if the batch had `answered_by_enabled` set to `true`. */
    answeredBy?: BlandAI.AnsweredByEnum;
}
