/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CallParams {
    reduceLatency: boolean;
    voiceId: number;
    language: string;
    requestData?: unknown;
    maxDuration: number;
    waitForGreeting: boolean;
}
