/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CallLengthSummary {
    "05": number;
    "510": number;
    "1015": number;
    "1520": number;
    "2030": number;
    "3045": number;
    "4560": number;
    "6090": number;
    "90120": number;
    "120": number;
}
