/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface ListBatchesResponse {
    /** Can be `success` or `error`. */
    status: string;
    /** An array of batch objects. */
    batches: BlandAI.BatchObject[];
}
