/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface QueueStatus {
    /** The number of completed calls in the batch. */
    complete?: number;
    /** The number of calls that are queued. */
    queued?: number;
    /** The number of calls that have an error. */
    callError?: number;
}
