/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface RetrieveBatchAnalysisResponse {
    /** Whether the request was successful or not. */
    status: BlandAI.StatusEnum;
    /** An error message or confirmation that the request was successful. */
    message: string;
    /** An array of analysis objects, each corresponding to a call within the batch. */
    analysis: BlandAI.BatchAnalysisObject[];
}
