/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type StatusEnum = "success" | "error";

export const StatusEnum = {
    Success: "success",
    Error: "error",
} as const;
