/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const AnalyzeBatchRequest: core.serialization.ObjectSchema<
    serializers.AnalyzeBatchRequest.Raw,
    BlandAI.AnalyzeBatchRequest
> = core.serialization.object({
    goal: core.serialization.string(),
    questions: core.serialization.list(core.serialization.list(core.serialization.string())),
});

export declare namespace AnalyzeBatchRequest {
    interface Raw {
        goal: string;
        questions: string[][];
    }
}
