/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const BatchAnalysisObject: core.serialization.ObjectSchema<
    serializers.BatchAnalysisObject.Raw,
    BlandAI.BatchAnalysisObject
> = core.serialization.object({
    callId: core.serialization.property("call_id", core.serialization.string()),
    batchId: core.serialization.property("batch_id", core.serialization.string()),
    goal: core.serialization.string(),
    answers: core.serialization.list(core.serialization.string()),
    questions: core.serialization.list(core.serialization.string()),
});

export declare namespace BatchAnalysisObject {
    interface Raw {
        call_id: string;
        batch_id: string;
        goal: string;
        answers: string[];
        questions: string[];
    }
}
