/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { BatchParams } from "./BatchParams";
import { AnalysisObject } from "./AnalysisObject";
import { CallData } from "./CallData";

export const BatchDetailsResponse: core.serialization.ObjectSchema<
    serializers.BatchDetailsResponse.Raw,
    BlandAI.BatchDetailsResponse
> = core.serialization.object({
    batchParams: core.serialization.property("batch_params", BatchParams),
    analysis: AnalysisObject,
    callData: core.serialization.property("call_data", core.serialization.list(CallData)),
});

export declare namespace BatchDetailsResponse {
    interface Raw {
        batch_params: BatchParams.Raw;
        analysis: AnalysisObject.Raw;
        call_data: CallData.Raw[];
    }
}
