/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { PhoneNumber } from "../../commons/types/PhoneNumber";

export const BatchCallData: core.serialization.ObjectSchema<serializers.BatchCallData.Raw, BlandAI.BatchCallData> =
    core.serialization.object({
        phoneNumber: core.serialization.property("phone_number", PhoneNumber),
        business: core.serialization.string().optional(),
        service: core.serialization.string().optional(),
        date: core.serialization.string().optional(),
    });

export declare namespace BatchCallData {
    interface Raw {
        phone_number: PhoneNumber.Raw;
        business?: string | null;
        service?: string | null;
        date?: string | null;
    }
}
