/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const CallParams: core.serialization.ObjectSchema<serializers.CallParams.Raw, BlandAI.CallParams> =
    core.serialization.object({
        reduceLatency: core.serialization.property("reduce_latency", core.serialization.boolean()),
        voiceId: core.serialization.property("voice_id", core.serialization.number()),
        language: core.serialization.string(),
        requestData: core.serialization.property("request_data", core.serialization.unknown()),
        maxDuration: core.serialization.property("max_duration", core.serialization.number()),
        waitForGreeting: core.serialization.property("wait_for_greeting", core.serialization.boolean()),
    });

export declare namespace CallParams {
    interface Raw {
        reduce_latency: boolean;
        voice_id: number;
        language: string;
        request_data?: unknown;
        max_duration: number;
        wait_for_greeting: boolean;
    }
}
