/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const CallLengthSummary: core.serialization.ObjectSchema<
    serializers.CallLengthSummary.Raw,
    BlandAI.CallLengthSummary
> = core.serialization.object({
    "05": core.serialization.property("0-5", core.serialization.number()),
    "510": core.serialization.property("5-10", core.serialization.number()),
    "1015": core.serialization.property("10-15", core.serialization.number()),
    "1520": core.serialization.property("15-20", core.serialization.number()),
    "2030": core.serialization.property("20-30", core.serialization.number()),
    "3045": core.serialization.property("30-45", core.serialization.number()),
    "4560": core.serialization.property("45-60", core.serialization.number()),
    "6090": core.serialization.property("60-90", core.serialization.number()),
    "90120": core.serialization.property("90-120", core.serialization.number()),
    "120": core.serialization.property("120+", core.serialization.number()),
});

export declare namespace CallLengthSummary {
    interface Raw {
        "0-5": number;
        "5-10": number;
        "10-15": number;
        "15-20": number;
        "20-30": number;
        "30-45": number;
        "45-60": number;
        "60-90": number;
        "90-120": number;
        "120+": number;
    }
}
