/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { CallLengthSummary } from "./CallLengthSummary";

export const CallLength: core.serialization.ObjectSchema<serializers.CallLength.Raw, BlandAI.CallLength> =
    core.serialization.object({
        average: core.serialization.number(),
        averageNonzero: core.serialization.property("average_nonzero", core.serialization.number()),
        summary: CallLengthSummary,
        all: core.serialization.list(core.serialization.number()),
    });

export declare namespace CallLength {
    interface Raw {
        average: number;
        average_nonzero: number;
        summary: CallLengthSummary.Raw;
        all: number[];
    }
}
