/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const QueueStatus: core.serialization.ObjectSchema<serializers.QueueStatus.Raw, BlandAI.QueueStatus> =
    core.serialization.object({
        complete: core.serialization.number().optional(),
        queued: core.serialization.number().optional(),
        callError: core.serialization.property("call_error", core.serialization.number().optional()),
    });

export declare namespace QueueStatus {
    interface Raw {
        complete?: number | null;
        queued?: number | null;
        call_error?: number | null;
    }
}
