/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const SendBatchResponse: core.serialization.ObjectSchema<
    serializers.SendBatchResponse.Raw,
    BlandAI.SendBatchResponse
> = core.serialization.object({
    message: core.serialization.string(),
    batchId: core.serialization.property("batch_id", core.serialization.string()),
});

export declare namespace SendBatchResponse {
    interface Raw {
        message: string;
        batch_id: string;
    }
}
