/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const StatusEnum: core.serialization.Schema<serializers.StatusEnum.Raw, BlandAI.StatusEnum> =
    core.serialization.enum_(["success", "error"]);

export declare namespace StatusEnum {
    type Raw = "success" | "error";
}
