/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const StopActiveBatchResponse: core.serialization.ObjectSchema<
    serializers.StopActiveBatchResponse.Raw,
    BlandAI.StopActiveBatchResponse
> = core.serialization.object({
    status: core.serialization.string(),
    message: core.serialization.string(),
    numCalls: core.serialization.property("num_calls", core.serialization.number()),
    batchId: core.serialization.property("batch_id", core.serialization.string()),
});

export declare namespace StopActiveBatchResponse {
    interface Raw {
        status: string;
        message: string;
        num_calls: number;
        batch_id: string;
    }
}
