/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../../../errors/index";
import * as BlandAI from "../../../index";

export class BadRequestError extends errors.BlandAIError {
    constructor(body: BlandAI.ErrorBody) {
        super({
            message: "BadRequestError",
            statusCode: 400,
            body: body,
        });
        Object.setPrototypeOf(this, BadRequestError.prototype);
    }
}
