/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface DeleteVoicePresetResponse {
    /** Confirmation message indicating successful deletion of the voice preset. */
    message: string;
    /** The ID of the voice preset that was deleted. */
    voice: string;
}
