/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface GenerateVoiceSampleResponse {
    /** The generated audio file of the spoken text using the specified or overridden voice preset settings. */
    sample?: unknown;
}
