/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface GenerateVoiceSampleRequest {
    /**
     * The text content to be spoken in the voice sample.
     *
     * Character limit: `200` characters.
     */
    text: string;
    /** Alternate `voice_settings` can be passed in to override the preset's default settings. */
    voiceSettings?: BlandAI.VoiceSettingsData;
}
