/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface ListVoiceOptionsResponse {
    /** Contains a list of the voices available for your account, including custom and default presets. */
    voices: BlandAI.Voice[];
    /** Contains a list of presets with their details. */
    presets: BlandAI.Preset[];
}
