/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type OptimizeFor = "speed_max" | "speed" | "quality" | "quality_max";

export const OptimizeFor = {
    SpeedMax: "speed_max",
    Speed: "speed",
    Quality: "quality",
    QualityMax: "quality_max",
} as const;
