/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Preset {
    voiceName: string;
    description: string;
    reduceLatency: boolean;
    interruptionThreshold?: number;
    language: string;
    voiceSettings?: unknown;
    editable: boolean;
    public: boolean;
    voicePresetId: string;
}
