/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface PublishVoicePresetResponse {
    /** Confirmation message indicating the successful publication of the voice preset. */
    message: string;
    /** Contains detailed information about the published voice preset. */
    voice: BlandAI.RetrievedVoice;
}
