/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RetrievedVoice {
    /** The unique identifier for the voice preset. */
    voicePresetId: string;
    /** Public voice name. */
    voiceName: string;
    /** The description of the voice preset. */
    description: string;
    /** Whether or not the voice preset is optimized for low latency. */
    reduceLatency: boolean;
    /** The threshold for the voice preset to be interrupted by a new message. */
    interruptionThreshold?: number;
    /** The language code of the voice preset. */
    language: string;
    /** The voice settings of the voice preset. */
    voiceSettings?: unknown;
    /** Whether or not your account can edit the preset. */
    editable: boolean;
    /** Whether or not the preset is publicly available. */
    public: boolean;
    /** The date and time the preset was originally created. */
    createdAt: Date;
}
