/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface RetrieveVoicePresetResponse {
    /** Contains detailed information about the specified voice preset. */
    voice: BlandAI.RetrievedVoice;
}
