/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface VoiceSettingsData {
    /** Multiplies the speed of the voice (only `reduce_latency: true` voices). */
    speed?: number;
    /** Delay before responding (in milliseconds). */
    interruptionThreshold?: number;
    /** Lower for more emotion, higher for more stability. */
    stability?: number;
    /** Match cloned voice more closely. */
    similarity?: number;
    /** Flexible pronunciation. */
    speechFlexibility?: number;
    /** The optimization setting for the voice. */
    optimizeFor?: BlandAI.OptimizeFor;
}
