/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface VoiceUpdates {
    /** The updated description of the voice preset. */
    description?: string;
    /** The updated voice settings, including optimization and interruption threshold. */
    voiceSettings?: BlandAI.VoiceSettingsData;
}
