/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { OutboundNumber } from "./OutboundNumber";

export const ListOutboundResponse: core.serialization.ObjectSchema<
    serializers.ListOutboundResponse.Raw,
    BlandAI.ListOutboundResponse
> = core.serialization.object({
    outboundNumbers: core.serialization.property("outbound_numbers", core.serialization.list(OutboundNumber)),
});

export declare namespace ListOutboundResponse {
    interface Raw {
        outbound_numbers: OutboundNumber.Raw[];
    }
}
