/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { PhoneNumber } from "../../commons/types/PhoneNumber";

export const OutboundPurchaseResponse: core.serialization.ObjectSchema<
    serializers.OutboundPurchaseResponse.Raw,
    BlandAI.OutboundPurchaseResponse
> = core.serialization.object({
    phoneNumber: core.serialization.property("phone_number", PhoneNumber),
});

export declare namespace OutboundPurchaseResponse {
    interface Raw {
        phone_number: PhoneNumber.Raw;
    }
}
