/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { PhoneNumber } from "../../commons/types/PhoneNumber";

export const OutboundNumber: core.serialization.ObjectSchema<serializers.OutboundNumber.Raw, BlandAI.OutboundNumber> =
    core.serialization.object({
        createdAt: core.serialization.property("created_at", core.serialization.date()),
        phoneNumber: core.serialization.property("phone_number", PhoneNumber),
        lastInitiated: core.serialization.property("last_initiated", core.serialization.date()),
    });

export declare namespace OutboundNumber {
    interface Raw {
        created_at: string;
        phone_number: PhoneNumber.Raw;
        last_initiated: string;
    }
}
