/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const OutboundPurchase: core.serialization.ObjectSchema<
    serializers.OutboundPurchase.Raw,
    BlandAI.OutboundPurchase
> = core.serialization.object({
    areaCode: core.serialization.property("area_code", core.serialization.string().optional()),
});

export declare namespace OutboundPurchase {
    interface Raw {
        area_code?: string | null;
    }
}
