/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         includeCalls: true,
 *         includeTranscripts: true,
 *         includeAnalysis: true
 *     }
 */
export interface BatchDetailsRequest {
    /**
     * Whether or not to include individual call data in the response.
     *
     * If no value is provided, `include_calls` defaults to `true`.
     */
    includeCalls?: boolean;
    /**
     * If calls are included, can be set to false to exclude transcripts from the response.
     *
     * If no value is provided, `include_transcripts` defaults to `true`.
     */
    includeTranscripts?: boolean;
    /**
     * If calls are included, can be set to false to exclude analysis from the response.
     *
     * If no value is provided, `include_analysis` defaults to `true`.
     */
    includeAnalysis?: boolean;
}
