/**
 * This file was auto-generated by Fern from our API Definition.
 */

export class BlandAITimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, BlandAITimeoutError.prototype);
    }
}
