/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const CountryCode: core.serialization.Schema<serializers.CountryCode.Raw, BlandAI.CountryCode> =
    core.serialization.enum_(["US", "GB", "CA"]);

export declare namespace CountryCode {
    type Raw = "US" | "GB" | "CA";
}
