/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { PhoneNumber } from "../../commons/types/PhoneNumber";
import { Webhook } from "../../commons/types/Webhook";
import { VoiceId } from "../../commons/types/VoiceId";

export const InboundNumberDetailsResponse: core.serialization.ObjectSchema<
    serializers.InboundNumberDetailsResponse.Raw,
    BlandAI.InboundNumberDetailsResponse
> = core.serialization.object({
    createdAt: core.serialization.property("created_at", core.serialization.string()),
    phoneNumber: core.serialization.property("phone_number", PhoneNumber),
    prompt: core.serialization.string(),
    webhook: Webhook,
    voiceId: core.serialization.property("voice_id", VoiceId),
    dynamicData: core.serialization.property("dynamic_data", core.serialization.string().optional()),
    maxDuration: core.serialization.property("max_duration", core.serialization.number()),
});

export declare namespace InboundNumberDetailsResponse {
    interface Raw {
        created_at: string;
        phone_number: PhoneNumber.Raw;
        prompt: string;
        webhook: Webhook.Raw;
        voice_id: VoiceId.Raw;
        dynamic_data?: string | null;
        max_duration: number;
    }
}
