/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { CountryCode } from "./CountryCode";
import { Webhook } from "../../commons/types/Webhook";
import { PhoneNumber } from "../../commons/types/PhoneNumber";

export const InboundNumberRequest: core.serialization.ObjectSchema<
    serializers.InboundNumberRequest.Raw,
    BlandAI.InboundNumberRequest
> = core.serialization.object({
    areaCode: core.serialization.property("area_code", core.serialization.string().optional()),
    prompt: core.serialization.string().optional(),
    countryCode: core.serialization.property("country_code", CountryCode.optional()),
    webhook: Webhook.optional(),
    phoneNumber: core.serialization.property("phone_number", PhoneNumber),
});

export declare namespace InboundNumberRequest {
    interface Raw {
        area_code?: string | null;
        prompt?: string | null;
        country_code?: CountryCode.Raw | null;
        webhook?: Webhook.Raw | null;
        phone_number: PhoneNumber.Raw;
    }
}
