/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { InboundNumber } from "./InboundNumber";

export const ListInboundResponse: core.serialization.ObjectSchema<
    serializers.ListInboundResponse.Raw,
    BlandAI.ListInboundResponse
> = core.serialization.object({
    response: core.serialization.list(InboundNumber),
});

export declare namespace ListInboundResponse {
    interface Raw {
        response: InboundNumber.Raw[];
    }
}
