/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const Model: core.serialization.Schema<serializers.Model.Raw, BlandAI.Model> = core.serialization.enum_([
    "base",
    "turbo",
    "enhanced",
]);

export declare namespace Model {
    type Raw = "base" | "turbo" | "enhanced";
}
