/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { Model } from "./Model";
import { PhoneNumber } from "../../commons/types/PhoneNumber";
import { VoiceId } from "../../commons/types/VoiceId";
import { Webhook } from "../../commons/types/Webhook";
import { Tools } from "../../commons/types/Tools";
import { VoiceSettings } from "./VoiceSettings";
import { CustomTool } from "../../commons/types/CustomTool";

export const UpdateInbound: core.serialization.ObjectSchema<serializers.UpdateInbound.Raw, BlandAI.UpdateInbound> =
    core.serialization.object({
        prompt: core.serialization.string(),
        transferList: core.serialization.property(
            "transfer_list",
            core.serialization.record(core.serialization.string(), core.serialization.string()).optional()
        ),
        model: Model.optional(),
        transferPhoneNumber: core.serialization.property("transfer_phone_number", PhoneNumber.optional()),
        voiceId: core.serialization.property("voice_id", VoiceId.optional()),
        webhook: Webhook.optional(),
        record: core.serialization.boolean().optional(),
        firstSentence: core.serialization.property("first_sentence", core.serialization.string().optional()),
        tools: Tools,
        voiceSettings: core.serialization.property("voice_settings", VoiceSettings.optional()),
        dynamicData: core.serialization.property("dynamic_data", core.serialization.string().optional()),
        interruptionThreshold: core.serialization.property(
            "interruption_threshold",
            core.serialization.number().optional()
        ),
        maxDuration: core.serialization.property("max_duration", core.serialization.number().optional()),
    });

export declare namespace UpdateInbound {
    interface Raw {
        prompt: string;
        transfer_list?: Record<string, string> | null;
        model?: Model.Raw | null;
        transfer_phone_number?: PhoneNumber.Raw | null;
        voice_id?: VoiceId.Raw | null;
        webhook?: Webhook.Raw | null;
        record?: boolean | null;
        first_sentence?: string | null;
        tools?: Tools.Raw;
        voice_settings?: VoiceSettings.Raw | null;
        dynamic_data?: string | null;
        interruption_threshold?: number | null;
        max_duration?: number | null;
    }
}
