/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const VoiceSettings: core.serialization.ObjectSchema<serializers.VoiceSettings.Raw, BlandAI.VoiceSettings> =
    core.serialization.object({
        stability: core.serialization.number().optional(),
        similarity: core.serialization.number().optional(),
        speed: core.serialization.number().optional(),
    });

export declare namespace VoiceSettings {
    interface Raw {
        stability?: number | null;
        similarity?: number | null;
        speed?: number | null;
    }
}
