/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { CustomTool } from "../../commons/types/CustomTool";

export const CreateWebAgentRequest: core.serialization.ObjectSchema<
    serializers.CreateWebAgentRequest.Raw,
    BlandAI.CreateWebAgentRequest
> = core.serialization.object({
    prompt: core.serialization.string(),
    voice: core.serialization.string().optional(),
    analysisSchema: core.serialization.property("analysis_schema", core.serialization.unknown().optional()),
    metadata: core.serialization.unknown().optional(),
    pathwayId: core.serialization.property("pathway_id", core.serialization.string().optional()),
    language: core.serialization.string().optional(),
    model: core.serialization.string().optional(),
    firstSentence: core.serialization.property("first_sentence", core.serialization.string().optional()),
    tools: core.serialization.list(CustomTool).optional(),
    dynamicData: core.serialization.property("dynamic_data", core.serialization.unknown().optional()),
    interruptionThreshold: core.serialization.property(
        "interruption_threshold",
        core.serialization.number().optional()
    ),
    maxDuration: core.serialization.property("max_duration", core.serialization.number().optional()),
});

export declare namespace CreateWebAgentRequest {
    interface Raw {
        prompt: string;
        voice?: string | null;
        analysis_schema?: unknown | null;
        metadata?: unknown | null;
        pathway_id?: string | null;
        language?: string | null;
        model?: string | null;
        first_sentence?: string | null;
        tools?: CustomTool.Raw[] | null;
        dynamic_data?: unknown | null;
        interruption_threshold?: number | null;
        max_duration?: number | null;
    }
}
