/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const CreateWebAgentResponse: core.serialization.ObjectSchema<
    serializers.CreateWebAgentResponse.Raw,
    BlandAI.CreateWebAgentResponse
> = core.serialization.object({
    status: core.serialization.string(),
    callId: core.serialization.property("call_id", core.serialization.string()),
});

export declare namespace CreateWebAgentResponse {
    interface Raw {
        status: string;
        call_id: string;
    }
}
