/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const A2PStatusEnum: core.serialization.Schema<serializers.A2PStatusEnum.Raw, BlandAI.A2PStatusEnum> =
    core.serialization.enum_(["pending", "approved", "failed"]);

export declare namespace A2PStatusEnum {
    type Raw = "pending" | "approved" | "failed";
}
