/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const CheckStatusRequest: core.serialization.ObjectSchema<
    serializers.CheckStatusRequest.Raw,
    BlandAI.CheckStatusRequest
> = core.serialization.object({
    registrationId: core.serialization.property("registration_id", core.serialization.string()),
});

export declare namespace CheckStatusRequest {
    interface Raw {
        registration_id: string;
    }
}
