/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { A2PStatusEnum } from "./A2PStatusEnum";

export const CheckStatusResponse: core.serialization.ObjectSchema<
    serializers.CheckStatusResponse.Raw,
    BlandAI.CheckStatusResponse
> = core.serialization.object({
    status: A2PStatusEnum,
    brandType: core.serialization.string(),
    failtureReason: core.serialization.string().optional(),
});

export declare namespace CheckStatusResponse {
    interface Raw {
        status: A2PStatusEnum.Raw;
        brandType: string;
        failtureReason?: string | null;
    }
}
