/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const GetMessagesResponse: core.serialization.ObjectSchema<
    serializers.GetMessagesResponse.Raw,
    BlandAI.GetMessagesResponse
> = core.serialization.object({
    messages: core.serialization.list(core.serialization.unknown()),
});

export declare namespace GetMessagesResponse {
    interface Raw {
        messages: unknown[];
    }
}
