/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { PhoneNumber } from "../../commons/types/PhoneNumber";

export const GetMessagesRequest: core.serialization.ObjectSchema<
    serializers.GetMessagesRequest.Raw,
    BlandAI.GetMessagesRequest
> = core.serialization.object({
    phoneNumber: core.serialization.property("phone_number", PhoneNumber.optional()),
    to: PhoneNumber.optional(),
    from: PhoneNumber.optional(),
});

export declare namespace GetMessagesRequest {
    interface Raw {
        phone_number?: PhoneNumber.Raw | null;
        to?: PhoneNumber.Raw | null;
        from?: PhoneNumber.Raw | null;
    }
}
