/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const LegalStructureEnum: core.serialization.Schema<
    serializers.LegalStructureEnum.Raw,
    BlandAI.LegalStructureEnum
> = core.serialization.enum_([
    "Partnership",
    "Limited Liability Corporation",
    "Co-operative",
    "Non-profit Corporation",
    "Corporation",
]);

export declare namespace LegalStructureEnum {
    type Raw =
        | "Partnership"
        | "Limited Liability Corporation"
        | "Co-operative"
        | "Non-profit Corporation"
        | "Corporation";
}
