/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const RegisterResponse: core.serialization.ObjectSchema<
    serializers.RegisterResponse.Raw,
    BlandAI.RegisterResponse
> = core.serialization.object({
    message: core.serialization.string(),
    data: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace RegisterResponse {
    interface Raw {
        message: string;
        data: Record<string, unknown>;
    }
}
