/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { PhoneNumber } from "../../commons/types/PhoneNumber";

export const ToggleReplyRequest: core.serialization.ObjectSchema<
    serializers.ToggleReplyRequest.Raw,
    BlandAI.ToggleReplyRequest
> = core.serialization.object({
    phoneNumber: core.serialization.property("phone_number", PhoneNumber.optional()),
    on: core.serialization.boolean().optional(),
});

export declare namespace ToggleReplyRequest {
    interface Raw {
        phone_number?: PhoneNumber.Raw | null;
        on?: boolean | null;
    }
}
