/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const ToggleReplyEnum: core.serialization.Schema<serializers.ToggleReplyEnum.Raw, BlandAI.ToggleReplyEnum> =
    core.serialization.enum_(["Turned human mode on", "Turned human mode off"]);

export declare namespace ToggleReplyEnum {
    type Raw = "Turned human mode on" | "Turned human mode off";
}
