/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { PhoneNumber } from "../../commons/types/PhoneNumber";

export const TrustedUser: core.serialization.ObjectSchema<serializers.TrustedUser.Raw, BlandAI.TrustedUser> =
    core.serialization.object({
        position: core.serialization.string().optional(),
        firstName: core.serialization.property("first_name", core.serialization.string().optional()),
        lastName: core.serialization.property("last_name", core.serialization.string().optional()),
        phoneNumber: core.serialization.property("phone_number", PhoneNumber.optional()),
        email: core.serialization.string().optional(),
    });

export declare namespace TrustedUser {
    interface Raw {
        position?: string | null;
        first_name?: string | null;
        last_name?: string | null;
        phone_number?: PhoneNumber.Raw | null;
        email?: string | null;
    }
}
