/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { PhoneNumber } from "../../commons/types/PhoneNumber";
import { Webhook } from "../../commons/types/Webhook";

export const UpdateWebhookRequest: core.serialization.ObjectSchema<
    serializers.UpdateWebhookRequest.Raw,
    BlandAI.UpdateWebhookRequest
> = core.serialization.object({
    phoneNumber: core.serialization.property("phone_number", PhoneNumber.optional()),
    webhook: Webhook.optional(),
});

export declare namespace UpdateWebhookRequest {
    interface Raw {
        phone_number?: PhoneNumber.Raw | null;
        webhook?: Webhook.Raw | null;
    }
}
