/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const UpdateWebhookResponse: core.serialization.ObjectSchema<
    serializers.UpdateWebhookResponse.Raw,
    BlandAI.UpdateWebhookResponse
> = core.serialization.object({
    status: core.serialization.string(),
});

export declare namespace UpdateWebhookResponse {
    interface Raw {
        status: string;
    }
}
