/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const UpdatePromptResponse: core.serialization.ObjectSchema<
    serializers.UpdatePromptResponse.Raw,
    BlandAI.UpdatePromptResponse
> = core.serialization.object({
    status: core.serialization.string(),
});

export declare namespace UpdatePromptResponse {
    interface Raw {
        status: string;
    }
}
