/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { PhoneNumber } from "../../commons/types/PhoneNumber";

export const UpdatePromptRequest: core.serialization.ObjectSchema<
    serializers.UpdatePromptRequest.Raw,
    BlandAI.UpdatePromptRequest
> = core.serialization.object({
    phoneNumber: core.serialization.property("phone_number", PhoneNumber.optional()),
    prompt: core.serialization.string().optional(),
});

export declare namespace UpdatePromptRequest {
    interface Raw {
        phone_number?: PhoneNumber.Raw | null;
        prompt?: string | null;
    }
}
