/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ModelEnum = "gpt4" | "base" | "turbo" | "enhanced";

export const ModelEnum = {
    Gpt4: "gpt4",
    Base: "base",
    Turbo: "turbo",
    Enhanced: "enhanced",
} as const;
