/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "Flight Status",
 *         data: "user.flights[0].status",
 *         context: "John's flight is currently Flight Status"
 *     }
 */
export interface ResponseData {
    /** A label for the fetched data. */
    name: string;
    /** The JSON path in the API response to extract the data from. */
    data: string;
    /** How this data should be incorporated into the AI's knowledge. */
    context: string;
}
