/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../index";

/**
 * @example
 *     {
 *         status: BlandAI.Status.Success,
 *         message: "Call successfully queued.",
 *         callId: "73c809a9-db35-4edb-8fa6-95a6a942daf8",
 *         batchId: undefined
 *     }
 */
export interface SendCallResponse {
    /** Can be `success` or `error`. */
    status: BlandAI.Status;
    /** A unique identifier for the call (present only if status is `success`). */
    callId?: BlandAI.CallId;
    /**
     * A unique identifier for the batcarrayh of calls (present only if status is `success`).
     *
     * If no batch is specified, this value will be `null`.
     */
    batchId?: string;
    /** A message describing the status of the call (present only if status is `success`). */
    message?: string;
}
