/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VoicemailAction = "hangup" | "leave_message";

export const VoicemailAction = {
    Hangup: "hangup",
    LeaveMessage: "leave_message",
} as const;
