/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface ListOutboundResponse {
    /** An array of outbound phone number objects. */
    outboundNumbers: BlandAI.OutboundNumber[];
}
