/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface OutboundPurchase {
    /**
     * Choose a three-digit area code for your phone number. If set as a parameter, a number will only be purchased by exact match if available.
     *
     * If no area code is set, the default `415` area code will be used.
     */
    areaCode?: string;
}
