/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface OutboundNumber {
    createdAt: Date;
    phoneNumber: BlandAI.PhoneNumber;
    lastInitiated: Date;
}
