/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         defaultOnly: true,
 *         presetsOnly: true,
 *         voicesOnly: true,
 *         isCustom: true,
 *         name: "string",
 *         voiceName: "string",
 *         voiceId: 1,
 *         reduceLatency: true,
 *         public: true,
 *         editable: true
 *     }
 */
export interface ListVoiceOptionsParams {
    /**
     * Filter to show only default presets, excluding user-created presets.
     */
    defaultOnly?: boolean;
    /**
     * Filter to show only presets.
     */
    presetsOnly?: boolean;
    /**
     * Filter to show only voices.
     */
    voicesOnly?: boolean;
    /**
     * Filter for custom voices.
     */
    isCustom?: boolean;
    /**
     * Filters the voices array by the name of the voice.
     */
    name?: string;
    /**
     * Filters the presets array by the name of the voice.
     */
    voiceName?: string;
    /**
     * Filters the presets array by the ID of the voice.
     */
    voiceId?: number;
    /**
     * Filter by latency reduction option. Use in tandem with `reduce_latency`to simulate exactly which voice your agent would use.
     */
    reduceLatency?: boolean;
    /**
     * Filter to show only public presets, or set to `false` to exclude them.
     */
    public?: boolean;
    /**
     * Filter to show only editable presets.
     */
    editable?: boolean;
}
