/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface AnalyzeCallResponse {
    /** Will be `success` if the request was successful. */
    status: BlandAI.Status;
    /** Confirms the request was successful, or provides an error message if the request failed. */
    message: string;
    /** Contains the analyzed answers for the call in an array. */
    answers: unknown[][];
    /**
     * Token-based price for the analysis request.
     *
     * As a rough estimate, the base cost is `0.003` credits with an additional `0.0015` credits per call in the call.
     *
     * Longer call transcripts and higher numbers of questions can increase the cost, however the cost scales very effectively with calls vs. individual calls.
     */
    creditsUsed: number;
}
