/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface AnalyzeCall {
    /** This is the overall purpose of the call. Provides context for the analysis to guide how the questions/transcripts are interpreted. */
    goal: BlandAI.Goal;
    /**
     * An array of questions to be analyzed for the call.
     *
     * Each question should be an array with two elements - the question text and the expected answer type (e.g., “string”, “boolean”).
     *
     * Fairly flexible in terms of the expected answer type, and unanswerable questions will default to `null`.
     */
    questions: string[][];
}
