/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AnsweredByEnum = "human" | "voicemail" | "unknown" | "no-answer";

export const AnsweredByEnum = {
    Human: "human",
    Voicemail: "voicemail",
    Unknown: "unknown",
    NoAnswer: "no-answer",
} as const;
