/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface AudioRecordingResponse {
    status: BlandAI.Status;
    /**
     * If the status is `success`, the `url` field will be present instead of this field.
     *
     * A 404 error will be returned if the call does not exist or the recording is not available. We can only retrieve recordings if the call was created with `record` set to `true`.
     *
     * A 400/500 error will be returned if there is an error retrieving the recording.
     */
    message?: string;
    /** If the status is `success`, the `url` will provide the exact location of the MP3 file storing the call's audio. */
    url?: string;
}
