/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface CallDetailsResponse {
    /** An array of phrases spoken during the call. */
    transcripts: BlandAI.Transcript[];
    /**
     * Variables created during the call - both system variables as well as generated with `dynamic_data`.
     *
     * For example, if you used a `dynamic_data` API request to generate a variable called `appointment_time`, you would see it here.
     */
    variables: Record<string, string>;
    /** A single string containing all of the text from the call. Excludes system messages and auto-generated data. */
    concatenatedTranscript: string;
    /** The phone number that received the call. */
    to: string;
    /** The phone number that made the call. */
    from: string;
    /** If the call is part of a batch, it's batch_id will be here. */
    batchId: string;
    /** Details about parameters in the original api request. */
    requestData: Record<string, string>;
    /** Whether the call has been completed. If it differs from the value of `queue_status`, this will be the most up-to-date status. */
    completed: boolean;
    /**
     * The status of the call. During extremely high volume periods, calls may be queued for a short period of time before being dispatched.
     *
     * Progresses through the following stages -
     *
     * - `new` - An API request has been received.
     * - `queued` - Call pararameters have been validated and authentication succeeded.
     * - `allocated` - Extremely brief, the call is being dispatched.
     * - `started` - The phone call is live and in progress.
     * - `complete` - The phone call has ended successfully.
     *
     * The following statuses show the point that was reached before an error -
     *
     * - `pre_queue_error` - An error occurred before the call was queued. Invalid parameters generally cause this.
     * - `queue_error` - Error occurred while the call was queued. Ex. Valid phone number but to an unserviced area.
     * - `call_error` - Error occurred during live call. May be caused by transferring to an invalid phone number or an unforeseen error.
     * - `complete_error` - Error occurred after the call was completed. Ex. A post-call webhook failed.
     *
     * If at any point an error occurs, it will be recorded in the `error_message` field.
     */
    queueStatus: string;
    /** If an error occurs, this will contain a description of the error. Otherwise, it will be null. */
    errorMessage: string;
    /**
     * If `answered_by_enabled` was set to `true` in the original API request, this field contains one of the following values:
     *
     * - `human`: The call was answered by a human.
     * - `voicemail`: The call was answered by an answering machine or voicemail.
     * - `unknown`: There was not enough audio at the start of the call to make a determination.
     * - `no-answer`: The call was not answered.
     * - `null`: Not enabled, or still processing the result.
     */
    answeredBy: BlandAI.AnsweredByEnum;
    /** The URL that was called to dispatch the phone call. */
    endpointUrl: string;
    /** The maximum length of time the call was allowed to last. If the call would exceed this length, it's ended early. */
    maxDuration: number;
    /** The total length of time the call was connected. This differs from `call_length` in that it includes ringing and connection time. */
    correctedDuration: number;
    /** The length of the call in minutes. */
    callLength: number;
    /** The timestamp for when the call was dispatched. */
    createdAt: Date;
}
