/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ListedCallData {
    callId: string;
    createdAt: Date;
    callLength: number;
    to: string;
    from: string;
    completed: boolean;
    queueStatus: string;
    errorMessage?: string;
    answeredBy: string;
    batchId?: string;
}
