/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface ListCallsResponse {
    /** The total number of calls returned in the response. */
    count: number;
    calls: BlandAI.ListedCallData[];
}
