/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface Transcript {
    id: string;
    createdAt: Date;
    text: string;
    user: BlandAI.UserEnum;
    /** The unique identifier for the call. */
    cId: string;
}
