/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UserEnum = "user" | "assistant" | "robot" | "agent-action";

export const UserEnum = {
    User: "user",
    Assistant: "assistant",
    Robot: "robot",
    AgentAction: "agent-action",
} as const;
