/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BlandAI from "../../api/index";
import * as core from "../../core";

export const InterruptionThreshold: core.serialization.Schema<
    serializers.InterruptionThreshold.Raw,
    BlandAI.InterruptionThreshold
> = core.serialization.number().optional();

export declare namespace InterruptionThreshold {
    type Raw = number | null | undefined;
}
