/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BlandAI from "../../api/index";
import * as core from "../../core";

export const MethodEnum: core.serialization.Schema<serializers.MethodEnum.Raw, BlandAI.MethodEnum> =
    core.serialization.enum_(["GET", "POST"]);

export declare namespace MethodEnum {
    type Raw = "GET" | "POST";
}
