/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BlandAI from "../../api/index";
import * as core from "../../core";

export const ModelEnum: core.serialization.Schema<serializers.ModelEnum.Raw, BlandAI.ModelEnum> =
    core.serialization.enum_(["gpt4", "base", "turbo", "enhanced"]);

export declare namespace ModelEnum {
    type Raw = "gpt4" | "base" | "turbo" | "enhanced";
}
