/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BlandAI from "../../api/index";
import * as core from "../../core";

export const PronunciationObject: core.serialization.ObjectSchema<
    serializers.PronunciationObject.Raw,
    BlandAI.PronunciationObject
> = core.serialization.object({
    word: core.serialization.string().optional(),
    pronunciation: core.serialization.string().optional(),
    caseInsensitive: core.serialization.property("case_insensitive", core.serialization.boolean().optional()),
    spaced: core.serialization.boolean().optional(),
});

export declare namespace PronunciationObject {
    interface Raw {
        word?: string | null;
        pronunciation?: string | null;
        case_insensitive?: boolean | null;
        spaced?: boolean | null;
    }
}
