/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BlandAI from "../../api/index";
import * as core from "../../core";
import { PronunciationObject } from "./PronunciationObject";

export const ProunciationGuide: core.serialization.Schema<
    serializers.ProunciationGuide.Raw,
    BlandAI.ProunciationGuide
> = core.serialization.list(PronunciationObject);

export declare namespace ProunciationGuide {
    type Raw = PronunciationObject.Raw[];
}
