/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BlandAI from "../../api/index";
import * as core from "../../core";

export const ResponseData: core.serialization.ObjectSchema<serializers.ResponseData.Raw, BlandAI.ResponseData> =
    core.serialization.object({
        name: core.serialization.string(),
        data: core.serialization.string(),
        context: core.serialization.string(),
    });

export declare namespace ResponseData {
    interface Raw {
        name: string;
        data: string;
        context: string;
    }
}
