/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BlandAI from "../../api/index";
import * as core from "../../core";
import { PhoneNumber } from "../resources/commons/types/PhoneNumber";
import { TransferList } from "./TransferList";
import { ModelEnum } from "./ModelEnum";
import { ProunciationGuide } from "./ProunciationGuide";
import { Temperature } from "./Temperature";
import { Tools } from "../resources/commons/types/Tools";
import { VoiceId } from "../resources/commons/types/VoiceId";
import { Webhook } from "../resources/commons/types/Webhook";
import { VoicemailAction } from "./VoicemailAction";
import { DynamicData } from "./DynamicData";
import { InterruptionThreshold } from "./InterruptionThreshold";
import { PronunciationObject } from "./PronunciationObject";
import { CustomTool } from "../resources/commons/types/CustomTool";

export const SendCall: core.serialization.ObjectSchema<serializers.SendCall.Raw, BlandAI.SendCall> =
    core.serialization.object({
        phoneNumber: core.serialization.property("phone_number", PhoneNumber),
        task: core.serialization.string(),
        transferList: core.serialization.property("transfer_list", TransferList.optional()),
        model: ModelEnum.optional(),
        pronunciationGuide: core.serialization.property("pronunciation_guide", ProunciationGuide.optional()),
        temperature: Temperature,
        tools: Tools,
        transferPhoneNumber: core.serialization.property("transfer_phone_number", PhoneNumber.optional()),
        answeredByEnabled: core.serialization.property("answered_by_enabled", core.serialization.boolean().optional()),
        from: core.serialization.string().optional(),
        reduceLatency: core.serialization.property("reduce_latency", core.serialization.boolean().optional()),
        voiceId: core.serialization.property("voice_id", VoiceId.optional()),
        voicePresetId: core.serialization.property("voice_preset_id", core.serialization.string().optional()),
        startTime: core.serialization.property("start_time", core.serialization.string().optional()),
        webhook: Webhook.optional(),
        waitForGreeting: core.serialization.property("wait_for_greeting", core.serialization.boolean().optional()),
        firstSentence: core.serialization.property("first_sentence", core.serialization.string().optional()),
        record: core.serialization.boolean().optional(),
        voiceSettings: core.serialization.property("voice_settings", core.serialization.boolean().optional()),
        language: core.serialization.string().optional(),
        maxDuration: core.serialization.property("max_duration", core.serialization.number().optional()),
        voicemailAction: core.serialization.property("voicemail_action", VoicemailAction.optional()),
        amd: core.serialization.boolean().optional(),
        requestData: core.serialization.property(
            "request_data",
            core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional()
        ),
        dynamicData: core.serialization.property("dynamic_data", core.serialization.list(DynamicData).optional()),
        interruptionThreshold: core.serialization.property("interruption_threshold", InterruptionThreshold),
    });

export declare namespace SendCall {
    interface Raw {
        phone_number: PhoneNumber.Raw;
        task: string;
        transfer_list?: TransferList.Raw | null;
        model?: ModelEnum.Raw | null;
        pronunciation_guide?: ProunciationGuide.Raw | null;
        temperature?: Temperature.Raw;
        tools?: Tools.Raw;
        transfer_phone_number?: PhoneNumber.Raw | null;
        answered_by_enabled?: boolean | null;
        from?: string | null;
        reduce_latency?: boolean | null;
        voice_id?: VoiceId.Raw | null;
        voice_preset_id?: string | null;
        start_time?: string | null;
        webhook?: Webhook.Raw | null;
        wait_for_greeting?: boolean | null;
        first_sentence?: string | null;
        record?: boolean | null;
        voice_settings?: boolean | null;
        language?: string | null;
        max_duration?: number | null;
        voicemail_action?: VoicemailAction.Raw | null;
        amd?: boolean | null;
        request_data?: Record<string, unknown> | null;
        dynamic_data?: DynamicData.Raw[] | null;
        interruption_threshold?: InterruptionThreshold.Raw;
    }
}
