/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BlandAI from "../../api/index";
import * as core from "../../core";

export const TransferList: core.serialization.Schema<serializers.TransferList.Raw, BlandAI.TransferList> =
    core.serialization.record(core.serialization.string(), core.serialization.string());

export declare namespace TransferList {
    type Raw = Record<string, string>;
}
