/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as BlandAI from "../../api/index";
import * as core from "../../core";

export const VoicemailAction: core.serialization.Schema<serializers.VoicemailAction.Raw, BlandAI.VoicemailAction> =
    core.serialization.enum_(["hangup", "leave_message"]);

export declare namespace VoicemailAction {
    type Raw = "hangup" | "leave_message";
}
