/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type CountryCode = "US" | "GB" | "CA";

export const CountryCode = {
    Us: "US",
    Gb: "GB",
    Ca: "CA",
} as const;
