/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface InboundNumber {
    createdAt: string;
    phoneNumber: BlandAI.PhoneNumber;
    prompt: string;
    webhook: BlandAI.Webhook;
    voiceId: BlandAI.VoiceId;
    dynamicData?: unknown[];
    interruptionThreshold?: number;
    firstSentence?: string;
    reduceLatency: boolean;
    transferPhoneNumber?: BlandAI.PhoneNumber;
    voiceSettings?: unknown;
    record: boolean;
    maxDuration: number;
}
