/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface InboundNumberDetailsResponse {
    /** The timestamp when the inbound number was configured. */
    createdAt: string;
    /** The specific inbound phone number. */
    phoneNumber: BlandAI.PhoneNumber;
    /** The prompt your agent is using. */
    prompt: string;
    webhook: BlandAI.Webhook;
    voiceId: BlandAI.VoiceId;
    /** Any dynamic data associated with the inbound number, if applicable. */
    dynamicData?: string;
    /** The maximum duration of a call to the inbound number, in minutes. */
    maxDuration: number;
}
