/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface ListInboundResponse {
    /** An array of objects, each representing an inbound phone number and its configuration. */
    response: BlandAI.InboundNumber[];
}
