/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Model = "base" | "turbo" | "enhanced";

export const Model = {
    Base: "base",
    Turbo: "turbo",
    Enhanced: "enhanced",
} as const;
