/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

/**
 * @example
 *     {
 *         prompt: "29382721828",
 *         transferList: {
 *             "default": "+1234567890",
 *             "sales": "+1234567890",
 *             "support": "+1234567890",
 *             "billing": "+1234567890"
 *         },
 *         model: BlandAI.Model.Enhanced
 *     }
 */
export interface UpdateInbound {
    /**
     * Provide instructions, relevant information, and examples of the ideal conversation flow.
     *
     * For inbound numbers, consider including additional context about the purpose of the call, and what types of callers to expect.
     *
     * **Best Practices:**
     *
     * **Out-of-the-Box Behaviors (Summarized):**
     *
     * - Speech pattern: Direct, concise, casual
     * - Spells out symbols, acronyms, abbreviations, percentages, etc. ($4,000,000 -> “four million dollars”)
     * - Asks clarifying questions
     *
     * **Prompting Tips:**
     *
     * Want to easily test out exactly how your agent will behave?
     *
     * - Try out Agent Testing!
     * - Aim for less than 2,000 characters where possible.
     * - Simple, direct prompts are the most predictable and reliable.
     * - Frame instructions positively:
     *   - `"Do this"` rather than `"Don't do this"`.
     *   - Ex. `“Keep the conversation casual”` rather than `“Don't be too formal”`.
     *   - This gives concrete examples of what to do, instead of leaving expected behavior open to interpretation.
     */
    prompt: string;
    /**
     * Give your agent the ability to transfer calls to a set of phone numbers.
     *
     * Overrides `transfer_phone_number` if a `transfer_list.default` is specified.
     *
     * Will default to `transfer_list.default`, or the chosen phone number.
     */
    transferList?: Record<string, string>;
    /**
     * Select a model to use for your call.
     *
     * If no model is provided, the default value `enhanced` will be used.
     *
     * In nearly all cases, `enhanced` is the best choice for now.
     *
     * Model Differences:
     *
     * There are three different ways to use Bland:
     *
     * - `model: base`
     *
     *   - The original, follows scripts/procedures most effectively.
     *   - Supports all features and capabilities.
     *   - Best for Custom Tools
     *
     * - `model: enhanced`
     *
     *   - Much faster latency and very conversational, works best with objective-based prompts.
     *   - Supports all features and capabilities.
     *
     * - `model: turbo`
     *   - The absolute fastest latency possible, can be verbose at times
     *   - Limited capabilities currently (excludes Transferring, IVR navigation, Custom Tools)
     *   - Extremely realistic conversation capabilities
     */
    model?: BlandAI.Model;
    /**
     * A phone number that the agent can transfer to under specific conditions - such as being asked to speak to a human or supervisor.
     *
     * Set to `null` to remove.
     *
     * Prompting Notes:
     *
     * - Specify conditions that the agent should transfer to a human under (examples are great!)
     * - In the `task`, refer to the action solely as “transfer” or “transferring”.
     * - Alternate phrasing such as “swap” or “switch” can mislead the agent, causing the action to be ignored.
     */
    transferPhoneNumber?: BlandAI.PhoneNumber;
    voiceId?: BlandAI.VoiceId;
    webhook?: BlandAI.Webhook;
    /**
     * To record your phone call, set record to `true`. When your call completes, you can access through the `recording_url` field in the call details or your webhook.
     *
     * If no value is provided, the default value `false` will be used.
     */
    record?: boolean;
    /**
     * A phrase that your call will start with instead of a generating one on the fly. This works both with and without `wait_for_greeting`. Can be more than one sentence, but must be less than 200 characters.
     *
     * To remove, set to `null` or an empty string.
     */
    firstSentence?: string;
    tools?: BlandAI.Tools;
    /**
     * Alter advanced voice settings for your agent.
     *
     * To remove, set to `null` or an empty string.
     */
    voiceSettings?: BlandAI.VoiceSettings;
    /**
     * Integrate data from external APIs into your agent's knowledge.
     *
     * Set to `null` or an empty string to clear dynamic data settings.
     *
     * Detailed usage in the Send Call endpoint.
     */
    dynamicData?: string;
    /**
     * How long our AI phone agent should wait in milliseconds before responding.
     *
     * When you increase the interruption latency, you force the AI phone agent to listen longer before responding. In practice, increasing the threshold results in less interruptions and more latency.
     *
     * Try setting the threshold to 500 milliseconds. You'll encounter higher latency, but you'll be interrupted less frequently.
     *
     * Set to `null` to reset to default.
     *
     * If no value is provided, the default value `50` will be used.
     */
    interruptionThreshold?: number;
    /**
     * The maximum duration in minutes that calls to your agent can last before being automatically terminated.
     *
     * Set to `null` to reset to default.
     *
     * If no value is provided, the default value `30` will be used.
     */
    maxDuration?: number;
}
