/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateInboundResponse {
    /** Whether the update was successful or not - will be `success` or `error`. */
    status: string;
    /** A message describing the status of the update. */
    message: string;
    /** An object containing the updated settings for the inbound number. */
    updates?: Record<string, unknown>;
    /** If the update was unsuccessful, this will contain the settings that failed to update. Useful to determine how your request is being interpreted on our end. */
    failedUpdates?: Record<string, string>;
}
