/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface VoiceSettings {
    /**
     * Note: This is an experimental parameter and may behave unexpectedly.
     *
     * Adjust the predictability and consistency of the AI agent's voice. Lower values allow larger deviations from the baseline voice, whether default or cloned. Setting this too high however can cause a monotone voice.
     *
     * Accepts decimal values between `0` and `1` (inclusive).
     */
    stability?: number;
    /**
     * Note: This is an experimental parameter and may behave unexpectedly.
     *
     * Higher values will make speech differences between the selected voice and others more prominent. Extremely high values can cause voice distortion.
     *
     * Use lower values to lower the distinctiveness of the voice or eliminate unwanted audio static spikes.
     *
     * Accepts decimal values between `0` and `1` (inclusive).
     */
    similarity?: number;
    /**
     * Note: This is an experimental parameter and may behave unexpectedly.
     *
     * Note #2: Setting `reduce_latency` to false will cause this parameter to be ignored.
     *
     * How fast your agent talks! This parameter is simply a speech-speed multiplier, and works with fractional values such as `0.5` or large ones like `2`.
     *
     * Accepts decimal values between `0.1` and `5` (inclusive).
     */
    speed?: number;
}
