/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         fromNumber: "string",
 *         toNumber: "string",
 *         from: 1,
 *         to: 1,
 *         limit: 1,
 *         ascending: true
 *     }
 */
export interface ListCallsRequest {
    /**
     * Filter calls by the number they were dispatched from.
     *
     * The number that initiated the call - the user's phone number for inbound calls, or the number your AI Agent called from for outbound calls.
     */
    fromNumber?: string;
    /**
     * Filter calls by the number they were dispatched to.
     *
     * The number that answered the call - the user's phone number for outbound calls, or your AI Agent's number for inbound calls.
     */
    toNumber?: string;
    /**
     * The starting index (inclusive) for the range of calls to retrieve.
     */
    from?: number;
    /**
     * The ending index for the range of calls to retrieve.
     */
    to?: number;
    /**
     * The maximum number of calls to return in the response.
     */
    limit?: number;
    /**
     * Whether to sort the calls in ascending order of their creation time.
     */
    ascending?: boolean;
}
