/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { Goal } from "./Goal";

export const AnalyzeCall: core.serialization.ObjectSchema<serializers.AnalyzeCall.Raw, BlandAI.AnalyzeCall> =
    core.serialization.object({
        goal: Goal,
        questions: core.serialization.list(core.serialization.list(core.serialization.string())),
    });

export declare namespace AnalyzeCall {
    interface Raw {
        goal: Goal.Raw;
        questions: string[][];
    }
}
