/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { Status } from "../../commons/types/Status";

export const AnalyzeCallResponse: core.serialization.ObjectSchema<
    serializers.AnalyzeCallResponse.Raw,
    BlandAI.AnalyzeCallResponse
> = core.serialization.object({
    status: Status,
    message: core.serialization.string(),
    answers: core.serialization.list(core.serialization.list(core.serialization.unknown())),
    creditsUsed: core.serialization.property("credits_used", core.serialization.number()),
});

export declare namespace AnalyzeCallResponse {
    interface Raw {
        status: Status.Raw;
        message: string;
        answers: unknown[][];
        credits_used: number;
    }
}
