/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const AnsweredByEnum: core.serialization.Schema<serializers.AnsweredByEnum.Raw, BlandAI.AnsweredByEnum> =
    core.serialization.enum_(["human", "voicemail", "unknown", "no-answer"]);

export declare namespace AnsweredByEnum {
    type Raw = "human" | "voicemail" | "unknown" | "no-answer";
}
