/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const Goal: core.serialization.Schema<serializers.Goal.Raw, BlandAI.Goal> = core.serialization.string();

export declare namespace Goal {
    type Raw = string;
}
