/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { Status } from "../../commons/types/Status";

export const StopCallResponse: core.serialization.ObjectSchema<
    serializers.StopCallResponse.Raw,
    BlandAI.StopCallResponse
> = core.serialization.object({
    status: Status,
    message: core.serialization.string(),
});

export declare namespace StopCallResponse {
    interface Raw {
        status: Status.Raw;
        message: string;
    }
}
