/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const UserEnum: core.serialization.Schema<serializers.UserEnum.Raw, BlandAI.UserEnum> = core.serialization.enum_(
    ["user", "assistant", "robot", "agent-action"]
);

export declare namespace UserEnum {
    type Raw = "user" | "assistant" | "robot" | "agent-action";
}
