/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const DeleteVoicePresetResponse: core.serialization.ObjectSchema<
    serializers.DeleteVoicePresetResponse.Raw,
    BlandAI.DeleteVoicePresetResponse
> = core.serialization.object({
    message: core.serialization.string(),
    voice: core.serialization.string(),
});

export declare namespace DeleteVoicePresetResponse {
    interface Raw {
        message: string;
        voice: string;
    }
}
