/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const GenerateVoiceSampleResponse: core.serialization.ObjectSchema<
    serializers.GenerateVoiceSampleResponse.Raw,
    BlandAI.GenerateVoiceSampleResponse
> = core.serialization.object({
    sample: core.serialization.unknown(),
});

export declare namespace GenerateVoiceSampleResponse {
    interface Raw {
        sample?: unknown;
    }
}
