/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { Voice } from "./Voice";
import { Preset } from "./Preset";

export const ListVoiceOptionsResponse: core.serialization.ObjectSchema<
    serializers.ListVoiceOptionsResponse.Raw,
    BlandAI.ListVoiceOptionsResponse
> = core.serialization.object({
    voices: core.serialization.list(Voice),
    presets: core.serialization.list(Preset),
});

export declare namespace ListVoiceOptionsResponse {
    interface Raw {
        voices: Voice.Raw[];
        presets: Preset.Raw[];
    }
}
