/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { RetrievedVoice } from "./RetrievedVoice";

export const PublishVoicePresetResponse: core.serialization.ObjectSchema<
    serializers.PublishVoicePresetResponse.Raw,
    BlandAI.PublishVoicePresetResponse
> = core.serialization.object({
    message: core.serialization.string(),
    voice: RetrievedVoice,
});

export declare namespace PublishVoicePresetResponse {
    interface Raw {
        message: string;
        voice: RetrievedVoice.Raw;
    }
}
