/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { RetrievedVoice } from "./RetrievedVoice";

export const RetrieveVoicePresetResponse: core.serialization.ObjectSchema<
    serializers.RetrieveVoicePresetResponse.Raw,
    BlandAI.RetrieveVoicePresetResponse
> = core.serialization.object({
    voice: RetrievedVoice,
});

export declare namespace RetrieveVoicePresetResponse {
    interface Raw {
        voice: RetrievedVoice.Raw;
    }
}
