/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { VoiceSettingsData } from "./VoiceSettingsData";

export const UpdateVoicePresetRequest: core.serialization.ObjectSchema<
    serializers.UpdateVoicePresetRequest.Raw,
    BlandAI.UpdateVoicePresetRequest
> = core.serialization.object({
    voiceName: core.serialization.property("voice_name", core.serialization.string().optional()),
    description: core.serialization.string().optional(),
    voiceId: core.serialization.property("voice_id", core.serialization.number().optional()),
    reduceLatency: core.serialization.property("reduce_latency", core.serialization.boolean().optional()),
    interruptionThreshold: core.serialization.property(
        "interruption_threshold",
        core.serialization.number().optional()
    ),
    language: core.serialization.string().optional(),
    voiceSettings: core.serialization.property("voice_settings", VoiceSettingsData.optional()),
});

export declare namespace UpdateVoicePresetRequest {
    interface Raw {
        voice_name?: string | null;
        description?: string | null;
        voice_id?: number | null;
        reduce_latency?: boolean | null;
        interruption_threshold?: number | null;
        language?: string | null;
        voice_settings?: VoiceSettingsData.Raw | null;
    }
}
