/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { VoiceUpdates } from "./VoiceUpdates";
import { RetrievedVoice } from "./RetrievedVoice";

export const UpdateVoicePresetResponse: core.serialization.ObjectSchema<
    serializers.UpdateVoicePresetResponse.Raw,
    BlandAI.UpdateVoicePresetResponse
> = core.serialization.object({
    message: core.serialization.string(),
    updates: VoiceUpdates,
    voice: RetrievedVoice,
});

export declare namespace UpdateVoicePresetResponse {
    interface Raw {
        message: string;
        updates: VoiceUpdates.Raw;
        voice: RetrievedVoice.Raw;
    }
}
