/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { OptimizeFor } from "./OptimizeFor";

export const VoiceSettingsData: core.serialization.ObjectSchema<
    serializers.VoiceSettingsData.Raw,
    BlandAI.VoiceSettingsData
> = core.serialization.object({
    speed: core.serialization.number().optional(),
    interruptionThreshold: core.serialization.property(
        "interruption_threshold",
        core.serialization.number().optional()
    ),
    stability: core.serialization.number().optional(),
    similarity: core.serialization.number().optional(),
    speechFlexibility: core.serialization.property("speech_flexibility", core.serialization.number().optional()),
    optimizeFor: core.serialization.property("optimize_for", OptimizeFor.optional()),
});

export declare namespace VoiceSettingsData {
    interface Raw {
        speed?: number | null;
        interruption_threshold?: number | null;
        stability?: number | null;
        similarity?: number | null;
        speech_flexibility?: number | null;
        optimize_for?: OptimizeFor.Raw | null;
    }
}
