/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CustomTool {
    /** The name of the tool. */
    name: string;
    /** A short explanation of what the tool does. */
    description: string;
    /** A JSON schema describing the input data. */
    inputSchema?: unknown;
    /** A string that will be spoken to the agent while your tool waits for a response. */
    speech?: string;
    /** An array of objects that describe how to extract data from the response. Within the response data, you can create variables that the phone agent can reference in its prompt. */
    responseData: unknown[];
}
