/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Formatting Notes:
 *
 * - The '+' or '%2B' prefix is optional.
 * - Will assume a US country code (+1) if no country code is provided.
 *
 * Valid Examples for +13334445555:
 *
 * - `%2B13334445555`
 * - `13334445555`
 * - `3334445555`
 *
 * @example
 *     "+18582814611"
 */
export type PhoneNumber = string;
