/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type Status =
    /**
     * The call was successfully initiated. */
    | "success"
    /**
     * The call was not successfully initiated. */
    | "error";

export const Status = {
    Success: "success",
    Error: "error",
} as const;
