/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

/**
 * Interact with the real world through API calls.
 *
 * Detailed tutorial here: [Custom Tools](https://docs.bland.ai/tutorials/custom-tools)
 */
export type Tools = BlandAI.CustomTool[] | undefined;
