/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Set your agent's voice - all available voices can be found with the List Voices endpoint.
 */
export type VoiceId = number;
