/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The webhook should be a `http` / `https` callback url. We will send the call_id and transcript to this URL after the call completes. This can be useful if you want to have real time notifications when calls finish.
 *
 * Set to `null` or an empty string to clear the webhook.
 */
export type Webhook = string;
