/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const BlandAIEnvironment = {
    Production: "https://api.bland.ai",
    Sandbox: "https://api.bland.ai",
} as const;

export type BlandAIEnvironment = typeof BlandAIEnvironment.Production | typeof BlandAIEnvironment.Sandbox;
