/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type A2PStatusEnum = "pending" | "approved" | "failed";

export const A2PStatusEnum = {
    Pending: "pending",
    Approved: "approved",
    Failed: "failed",
} as const;
