/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface CheckStatusResponse {
    status: BlandAI.A2PStatusEnum;
    /** The brand type of the A2P registration. */
    brandType: string;
    /** The reason the A2P registration failed. */
    failtureReason?: string;
}
