/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface GetMessagesRequest {
    /** The phone number to get messages for. */
    phoneNumber?: BlandAI.PhoneNumber;
    /** The to number in the conversation. This is the number you _do not_ own. */
    to?: BlandAI.PhoneNumber;
    /** The from number in the conversation. This is the number you _do_ own. */
    from?: BlandAI.PhoneNumber;
}
