/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type LegalStructureEnum =
    | "Partnership"
    | "Limited Liability Corporation"
    | "Co-operative"
    | "Non-profit Corporation"
    | "Corporation";

export const LegalStructureEnum = {
    Partnership: "Partnership",
    LimitedLiabilityCorporation: "Limited Liability Corporation",
    Cooperative: "Co-operative",
    NonProfitCorporation: "Non-profit Corporation",
    Corporation: "Corporation",
} as const;
