/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface RegisterRequest {
    /** The legal name of your business. */
    businessName: string;
    /** Your Employer Identification Number. */
    ein: string;
    /** The industry vertical of your business. */
    vertical: BlandAI.VerticalEnum;
    /** The business address. */
    address: string;
    /** The city of your business. */
    city: string;
    /** The state of your business. Must be a valid US state code. */
    state: string;
    /** The postal code of your business. */
    postalCode: string;
    /** The country of your business. */
    country: string;
    /** The email address for your business. */
    email: string;
    /** Legal structure of the business. */
    type: BlandAI.LegalStructureEnum;
    /** Your business's website URL. */
    website: string;
    /**
     * Information regarding opt-in procedures for your messaging service.
     *
     * EX: “Customers must explicitly consent on our website and during the phone call.”
     */
    optInInfo: string;
    /** An array of three strings, each a sample message you plan to use. */
    messageSamples: string[];
    /** An object containing details about the trusted user registering the brand. */
    trustedUser: BlandAI.TrustedUser;
}
