/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface ToggleReplyRequest {
    /** The phone number to update. */
    phoneNumber?: BlandAI.PhoneNumber;
    /**
     * Turn human mode on or off.
     *
     * `true` means that the AI will not reply. `false` means the AI will reply.
     */
    on?: boolean;
}
