/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface ToggleReplyResponse {
    /** A message indicating the success of the request. */
    message: BlandAI.ToggleReplyEnum;
}
