/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ToggleReplyEnum = "Turned human mode on" | "Turned human mode off";

export const ToggleReplyEnum = {
    On: "Turned human mode on",
    Off: "Turned human mode off",
} as const;
