/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface TrustedUser {
    position?: string;
    firstName?: string;
    lastName?: string;
    phoneNumber?: BlandAI.PhoneNumber;
    email?: string;
}
