/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface UpdateWebhookRequest {
    /** The phone number to update. */
    phoneNumber?: BlandAI.PhoneNumber;
    /** The webhook to fire when an SMS is received. */
    webhook?: BlandAI.Webhook;
}
