/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface UpdatePromptRequest {
    /** The phone number to update. */
    phoneNumber?: BlandAI.PhoneNumber;
    /** The prompt for the AI to use when replying. */
    prompt?: string;
}
