/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type VerticalEnum =
    | "AUTOMOTIVE"
    | "AGRICULTURE"
    | "BANKING"
    | "CONSTRUCTION"
    | "CONSUMER"
    | "EDUCATION"
    | "ENGINEERING"
    | "ENERGY"
    | "OIL_AND_GAS"
    | "FAST_MOVING_CONSUMER_GOODS"
    | "FINANCIAL"
    | "FINTECH"
    | "FOOD_AND_BEVERAGE"
    | "GOVERNMENT"
    | "HEALTHCARE"
    | "HOSPITALITY"
    | "INSURANCE"
    | "LEGAL"
    | "MANUFACTURING"
    | "MEDIA"
    | "ONLINE"
    | "PROFESSIONAL_SERVICES"
    | "RAW_MATERIALS"
    | "REAL_ESTATE"
    | "RELIGION"
    | "RETAIL"
    | "JEWELRY"
    | "TECHNOLOGY"
    | "TELECOMMUNICATIONS"
    | "TRANSPORTATION"
    | "TRAVEL"
    | "ELECTRONICS"
    | "NOT_FOR_PROFIT";

export const VerticalEnum = {
    Automotive: "AUTOMOTIVE",
    Agriculture: "AGRICULTURE",
    Banking: "BANKING",
    Construction: "CONSTRUCTION",
    Consumer: "CONSUMER",
    Education: "EDUCATION",
    Engineering: "ENGINEERING",
    Energy: "ENERGY",
    OilAndGas: "OIL_AND_GAS",
    FastMovingConsumerGoods: "FAST_MOVING_CONSUMER_GOODS",
    Financial: "FINANCIAL",
    Fintech: "FINTECH",
    FoodAndBeverage: "FOOD_AND_BEVERAGE",
    Government: "GOVERNMENT",
    Healthcare: "HEALTHCARE",
    Hospitality: "HOSPITALITY",
    Insurance: "INSURANCE",
    Legal: "LEGAL",
    Manufacturing: "MANUFACTURING",
    Media: "MEDIA",
    Online: "ONLINE",
    ProfessionalServices: "PROFESSIONAL_SERVICES",
    RawMaterials: "RAW_MATERIALS",
    RealEstate: "REAL_ESTATE",
    Religion: "RELIGION",
    Retail: "RETAIL",
    Jewelry: "JEWELRY",
    Technology: "TECHNOLOGY",
    Telecommunications: "TELECOMMUNICATIONS",
    Transportation: "TRANSPORTATION",
    Travel: "TRAVEL",
    Electronics: "ELECTRONICS",
    NotForProfit: "NOT_FOR_PROFIT",
} as const;
