/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateWebAgentResponse {
    /** Can be success or error. */
    status: string;
    /** A unique identifier for the call (present only if status is success). */
    callId: string;
}
