/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BlandAI from "../../../index";

export interface CreateWebAgentRequest {
    /** Provide instructions, relevant information, and examples of the ideal conversation flow. */
    prompt: string;
    /** Set your agent's voice - all available voices can be found with the [List Voices](https://docs.bland.ai/api-v1/get/voices) endpoint. */
    voice?: string;
    /**
     * Define a JSON schema for how you want to get information about the call - information like email addresses, names, appointment times or any other type of custom data.
     *
     * In the webhook response or whenever you retrieve call data later, you’ll get the data you defined back under analysis.
     */
    analysisSchema?: unknown;
    /** Add any additional information you want to associate with the call. This can be useful for tracking or categorizing calls. */
    metadata?: unknown;
    /**
     * Set the pathway that your agent will follow. This will override the prompt field, so there is no need to pass the ‘prompt’ field if you are setting a pathway.
     *
     * Warning: Setting a pathway will set the following fields to null / their default value - prompt, first_sentence, model, dynamic_data, tools
     *
     * Set to null or an empty string to clear the pathway.
     */
    pathwayId?: string;
    /**
     * Select a supported language of your choice. Optimizes every part of our API for that language - transcription, speech, and other inner workings.
     *
     * Supported Languages and their codes:
     *
     * English: ENG
     * Spanish: ESP
     * French: FRE
     * Polish: POL
     * German: GER
     * Italian: ITA
     * Brazilian Portuguese: PBR
     * Portuguese: POR
     */
    language?: string;
    /**
     * Select a model to use for your call.
     *
     * Options: base, turbo and enhanced.
     *
     * In nearly all cases, enhanced is the best choice for now.
     */
    model?: string;
    /**
     * A phrase that your call will start with instead of a generating one on the fly. This works both with and without wait_for_greeting. Can be more than one sentence, but must be less than 200 characters.
     *
     * To remove, set to null or an empty string.
     */
    firstSentence?: string;
    /**
     * Interact with the real world through API calls.
     *
     * Detailed tutorial here: [Custom Tools](https://docs.bland.ai/tutorials/custom-tools)
     */
    tools?: BlandAI.CustomTool[];
    /**
     * Integrate data from external APIs into your agent’s knowledge.
     *
     * Set to null or an empty string to clear dynamic data settings.
     *
     * Detailed usage in the [Send Call](https://docs.bland.ai/api-v1/post/calls) endpoint.
     */
    dynamicData?: unknown;
    /**
     * When you increase the interruption latency, you force the AI phone agent to listen longer before responding. In practice, increasing the threshold results in less interruptions and more latency.
     *
     * Try setting the threshold to 500 milliseconds. You’ll encounter higher latency, but you’ll be interrupted less frequently.
     *
     * Set to null to reset to default.
     */
    interruptionThreshold?: number;
    /**
     * Set the maximum duration of the call in seconds. The call will be automatically disconnected after this time.
     *
     * Set to null to reset to default.
     */
    maxDuration?: number;
}
