/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const CallId: core.serialization.Schema<serializers.CallId.Raw, BlandAI.CallId> = core.serialization
    .string()
    .optional();

export declare namespace CallId {
    type Raw = string | null | undefined;
}
