/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const CustomTool: core.serialization.ObjectSchema<serializers.CustomTool.Raw, BlandAI.CustomTool> =
    core.serialization.object({
        name: core.serialization.string(),
        description: core.serialization.string(),
        inputSchema: core.serialization.property("input_schema", core.serialization.unknown()),
        speech: core.serialization.string().optional(),
        responseData: core.serialization.property(
            "response_data",
            core.serialization.list(core.serialization.unknown())
        ),
    });

export declare namespace CustomTool {
    interface Raw {
        name: string;
        description: string;
        input_schema?: unknown;
        speech?: string | null;
        response_data: unknown[];
    }
}
