/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const ErrorBody: core.serialization.ObjectSchema<serializers.ErrorBody.Raw, BlandAI.ErrorBody> =
    core.serialization.object({
        status: core.serialization.string(),
        message: core.serialization.string(),
    });

export declare namespace ErrorBody {
    interface Raw {
        status: string;
        message: string;
    }
}
