/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const PhoneNumber: core.serialization.Schema<serializers.PhoneNumber.Raw, BlandAI.PhoneNumber> =
    core.serialization.string();

export declare namespace PhoneNumber {
    type Raw = string;
}
