/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const Status: core.serialization.Schema<serializers.Status.Raw, BlandAI.Status> = core.serialization.enum_([
    "success",
    "error",
]);

export declare namespace Status {
    type Raw = "success" | "error";
}
