/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";
import { CustomTool } from "./CustomTool";

export const Tools: core.serialization.Schema<serializers.Tools.Raw, BlandAI.Tools> = core.serialization
    .list(CustomTool)
    .optional();

export declare namespace Tools {
    type Raw = CustomTool.Raw[] | null | undefined;
}
