/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index";
import * as BlandAI from "../../../../api/index";
import * as core from "../../../../core";

export const Webhook: core.serialization.Schema<serializers.Webhook.Raw, BlandAI.Webhook> = core.serialization.string();

export declare namespace Webhook {
    type Raw = string;
}
